version: '3'

services:
  scala:
    build: .
    command: sbt run
    environment:
      KAFKA_HOST: kafka:9092
      KAFKA_GROUP_ID: develop_consumer_group
    depends_on:
      - kafka
    volumes:
      - .:/broker
      - ./.ivy2:/root/.ivy2
      - ./.sbt:/root/.sbt
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:1.1.0
    hostname: kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

